# Esse workflow irá instalar dependências do Python, executar testes e analisar a qualidade do código.

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
        
    - name: Install Test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 . --exit-zero
        
    - name: Run pytest
      env:
        COLLECTION_ID: ${{secrets.COLLECTION_ID}}
        FACES_BUCKET: ${{secrets.FACES_BUCKET}}
        SITE_BUCKET: ${{secrets.SITE_BUCKET}}
      run: |
        pytest -v tests --cov --cov-report=xml --cov-report=html
    
    - name: Install local app dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
          
    - name: Delete unnecessary build files
      run: | 
        rm -rf .pytest_cache
        rm -rf .venv
        rm -rf __pycache__
        rm -rf *.dist-info
        rm -rf *.egg-info
    
    - name: Zip Artifacts
      run: | 
        zip -r deploy.zip .
    
    - name: Deploy to AWS
      env:
        LAMBDA: ${{secrets.LAMBDA}}
      run: aws lambda update-function-code --function-name=$LAMBDA --zip-file=fileb://deploy.zip
